companieshouse/chips-weblogic-batch

weblogic-batch/psc-pursuit-trigger/psc-pursuit-trigger.sh

When using -jar option the JAR file is source of all user classes but
other user class path settings are ignored.
As no class path entries are defined in this jar manifest so must
specify all on command line via this syntax to avoid
java.lang.NoClassDefFoundError errors.

Switched from using -jar execution to -cp

---

Dockerfile
weblogic-batch/.msmtprc.template
weblogic-batch/batchmanager/batchmanager.sh
weblogic-batch/bulk-image-load/bulk-image-load.properties.template
weblogic-batch/bulk-image-load/bulk-image-load.sh
weblogic-batch/bulk-image-load/clear-cloud-images-dir.sh
weblogic-batch/bulk-image-load/count_image_api_in_table.command
weblogic-batch/bulk-image-load/remove_duplicates_from_image_api_in_table.command
weblogic-batch/cron/crontab.txt
weblogic-batch/scripts/alert_functions
weblogic-batch/scripts/check-for-jms-message.sh
weblogic-batch/setCron.sh

First pass at adding bulk image load based on scripts running in prod
Overnight cleanup script clear-cloud-images-dir.sh based on current clearAppsBeaCloudImagesDir.sh
(with email sending & DB reinsertion removed as Jake advised no longer required)
Main job (DB checks + JMS trigger) bulk-image-load.sh based on current bulkimageload.sh
For DB connections, added yum install of packages required for sqlplus
For email sending, added yum install of packages required for msmtp & a .msmptrc config file
Created a scripts dir for shared use containing alert_functions & check-for-jms-message.sh
These changes require the following additional environment setup:
chips.properties:
CHIPS_SQLPLUS_CONN_STRING="usr/pwd@host:port/servicename"
JMS_SERVER_NAME="JMSServer1"
WEBLOGIC_ADMIN_USERNAME="weblogic" …

CM-1102 chips weblogic batch configuration for bulkimageload

---

Dockerfile

Switched from libs-release to virtual-release use on basis of guidance that libs-release intended to be for internal artifacts

CM-1100: Added log4j 2 jars required for image-regeneration

---

Dockerfile
weblogic-batch/psc-pursuit-trigger/log4j2.xml
weblogic-batch/psc-pursuit-trigger/psc-pursuit-trigger.sh

Dockerfile update brings in log4j2 psc-pursuit-trigger version.
Sole console appender in log4j2.xml to log to file per the invocation
based convention defined in psc-pursuit-trigger.sh.
Adopts use of -Dlog4j.configurationFile  over -Dlog4j.configuration for
log4j2 file designation.
Tweak to use 'date --iso-8601=seconds' to help standardize date logging
across shell and application.
e.g.
2022-03-01T16:44:55+0000 Starting psc-pursuit-trigger
2022-03-01T16:44:55,989 [main]  INFO  - ----------
2022-03-01T16:44:55,999 [main]  INFO  - Psc Pursuit trigger invoked ...

CM-1098: Update to use log4j2 version of psc-pursuit-trigger

---

Dockerfile
weblogic-batch/cron/crontab.txt
weblogic-batch/officer-bulk-process/bulk-officer.xml
weblogic-batch/officer-bulk-process/check--10000-exists.sh
weblogic-batch/officer-bulk-process/check-bpp-timestamps-order.command
weblogic-batch/officer-bulk-process/check-lock-file-reminder.sh
weblogic-batch/officer-bulk-process/check-officer-merge-finished.command
weblogic-batch/officer-bulk-process/check-officer-publish-finished.command
weblogic-batch/officer-bulk-process/log4j2.xml
weblogic-batch/officer-bulk-process/officer-bulk-process.sh
weblogic-batch/officer-bulk-process/officer-poller.properties.template
weblogic-batch/officer-bulk-process/reset-director-bpp.command
weblogic-batch/scripts/alert_functions

Initial commit to add officer scripts to weblogic batch (crontab entries
commented out for now).
Main script officer-bulk-process.sh is copied from existing script
officer.catchup.sh, but added an optional parameter so that current
scripts for partial runs can use the main script (e.g. calling
"./officer-bulk-process.sh 23" replaces the current
officer.catchup.STAGE.2.3.sh).
Also fixed a typo (missing underscore in the property name
EMAIL_ADDRESS_SERVICE_NOW) in alert_functions script.

CM-1101 initial checkin for adding officer scripts

---

weblogic-batch/psc-pursuit-trigger/psc-pursuit-trigger.sh

Core change to integrate with notification mechanism to notify CSI/ServiceNow via email upon failure to complete script.
Added logging functions to add timestamps to log entries.
Minor script updates for safety.
Defenesive change to stop script if no psc-pursuit-trigger dir exists.

CM-1299: Add alerting via email/ServiceNow for core failure

---

weblogic-batch/officer-bulk-process/officer-bulk-process.sh

Moving check for completed PUBLISH stage inside stage 1 (event) section to allow for deliberate retry attempts (e.g. re-running stage 3 in isolation when this is in an incomplete state).

Only check PUBLISH stage finished in EVENT stage

---

Dockerfile
weblogic-batch/cron/crontab.txt
weblogic-batch/image-regeneration/fesImageRegenerateClient.sh
weblogic-batch/image-regeneration/image-regeneration.sh
weblogic-batch/image-regeneration/imageRegenerateClient.sh
weblogic-batch/letter-producer/bad-letters.sh
weblogic-batch/letter-producer/letter-counts.sh
weblogic-batch/letter-producer/letter-producer.properties.template
weblogic-batch/letter-producer/letter-producer.sh
weblogic-batch/officer-bulk-process/officer-bulk-process-single.sh
weblogic-batch/officer-bulk-process/officer-bulk-process.sh
weblogic-batch/psc-pursuit-trigger/psc-pursuit-trigger.sh
weblogic-batch/scripts/check-for-jms-message.sh
weblogic-batch/scripts/logging_functions

Note: PR one-way diff is confusing due to my merge from main branch before committing - for a clear diff between current main & feature/letter-producer branch ignoring merged commits, see https://github.com/companieshouse/chips-weblogic-batch/compare/main..feature/letter-producer
- Using /apps/oracle/chipsdomain/batch/ as path to output files - this
will need to be configured as a bind volume here & in wlserver
container(s) in docker-compose.yml; also requires chips.properties entry
JMS_LETTERPRODUCERQUEUE="uk.gov.ch.chips.jms.LetterProducerQueue"
- Starting to use standard logging functions (incomplete: queries on
multi-line output & whether alert log file requires a specific format)
- Minor fixes for function call syntax
Some refactoring may be required when adding process compliance …

CM-1106 Letter producer

---

Dockerfile
weblogic-batch/compliance-trigger/compliance-trigger.properties.template
weblogic-batch/compliance-trigger/compliance-trigger.sh
weblogic-batch/compliance-trigger/log4jconfig.xml
weblogic-batch/cron/crontab.txt

Initial check-in for compliance trigger.
- May require some refactoring when process compliance script added
(marked as TODO).
- Initial local tests have shown it populating COMPLIANCE_STAGE table in
CHIPS with added param -999 to stop any onward processing; will require
fuller tests (including staffware updates) in staging.
- Requires new chips.properties entries:
COMPLIANCE_TRIGGER_DELAY="0"
COMPLIANCE_TRIGGER_IPDETECT="false"
COMPLIANCE_TRIGGER_PAUSE="90"
COMPLIANCE_TRIGGER_EVENTLIMIT="25000"
COMPLIANCE_TRIGGER_CASESATONCE="300"

CM-1105 Initial commit for compliance trigger

---

Dockerfile
weblogic-batch/doc1-producer/doc1-producer-config.xml
weblogic-batch/doc1-producer/doc1-producer.properties.template
weblogic-batch/doc1-producer/doc1-producer.sh
weblogic-batch/scripts/logging_functions

Initial commit of doc1-producer files - as with others, includes a TODO
for finalising logging etc once process compliance script added.
Properties file template includes some hardcoded values - will
investigate & update this to source these from chips.properties if they
appear likely to change.
Minor edits to logging_functions script
- using date format with milliseconds to match log4j output
- adding the name of the calling script to the log lines
E.g. output:
2022-04-27T14:55:35,575 [doc1-producer.sh] INFO  Starting doc1-producer

CM-1107 doc1-producer initial commit + log tweaks

---

Dockerfile
weblogic-batch/admin/jms/README.md
weblogic-batch/admin/jms/move-jms.sh
weblogic-batch/admin/jms/reprocess-jms.sh
weblogic-batch/cron/crontab.txt

Added scripts in /apps/oracle/admin/jms that allow moving of JMS messages from one queue to another.
Added cron entries to run the resubmission of specific queues, from the error queue to the processing queue, as per on-prem crontab.
The main script is reprocess-jms.sh and that takes parameters (see readme or script) that specify the queues to move messages to/from.  The script also needs at least one JMS_SERVER_# environment variable, that determines which server(s) to move the messages on.  This allows for environmental differences and to reprocess messages on several clusters by running one script.
Resolves: https://companieshouse.atlassian.net/browse/CM-1332

Add JMS resubmission scripts and cron entries

---

weblogic-batch/admin/jms/README.md
weblogic-batch/admin/jms/reprocess-jms.sh

The resubmission script was looking for any environment variables that start with `JMS_SERVER_` but there is an existing var `JMS_SERVER_NAME` that was being picked up and shouldn't be.
This updates the script to change the vars that are used to be `JMS_SERVER_URL_*` instead
Resolves: https://companieshouse.atlassian.net/browse/CM-1332

Filter out unrelated JMS_SERVER_NAME env var

---

weblogic-batch/admin/jms/report-stuck-ef-submissions.sh

This resolves an issue with parsing large xml files, which was failing for some documents such as MR01s.
Resolves: https://companieshouse.atlassian.net/browse/CM-1330

Remove attachment data from xml before parsing

---

weblogic-batch/admin/jms/report-stuck-ef-submissions.sh
weblogic-batch/cron/crontab.txt
weblogic-batch/scripts/alert_functions

Email report for stuck docs to csi & servicenow in the mornings, and override to just send to csi in the afternoons.
Resolves: https://companieshouse.atlassian.net/browse/CM-1330

Allow override of email address for stuck docs report

---

weblogic-batch/cron/crontab.txt
weblogic-batch/letter-producer/letter-counts.sh
weblogic-batch/process-compliance/process-compliance.sh

- call letter-counts.sh script from process-compliance.sh script instead
of from cron so that it is sent as soon as the files are available
- retry after a one minute sleep when a write to the gateway fails, and
notify CSI via an email if the 2nd attempt fails

CM-1104 script changes after recent live issues

---

weblogic-batch/setCron.sh

Constructing property CHIPS_SQLPLUS_CONN_STRING from existing props
rather than using a separate property that has to be kept in synch.
Appending to env.variables file as part of setCron.sh setup so that
existing scripts can use it unchanged.

CM-1415 derive property CHIPS_SQLPLUS_CONN_STRING

---

weblogic-batch/cron/crontab.txt

Reverts companieshouse/chips-weblogic-batch#47
Reverting as a safety measure while we decide a way forward, to prevent a future build accidentally rolling this change out.

Revert "Enable process compliance jobs"

---

weblogic-batch/admin/jms/README.md
weblogic-batch/admin/jms/report-stuck-chips-generic-messages.sh
weblogic-batch/admin/jms/report-stuck-ef-submissions.sh

Adds a new script, `report-stuck-chips-generic-messages.sh`, that emails out a list of any JMS messages that are stuck in the ChipsGenericErrorQueue.
Resolves: https://companieshouse.atlassian.net/browse/CM-1454

Report stuck JMS messages in ChipsGenericErrorQueue

---

weblogic-batch/doc1-producer/doc1-producer.sh

As a precautionary measure, we want to limit the memory used by the doc1Producer job - this normally only uses around 3-400K so a limit of 1G is ample.
Also sets a umask of 000, as a temporary measure, to allow other users to archive/tidy away the output files.

Limit max heap and set umask

---

weblogic-batch/letter-producer/check-letter-producer-2nd-phase.sh
weblogic-batch/scripts/alert_functions

Copied (slightly simplified) functionality from prior on-prem check into cloud. Not bringing 6am 'DONT SHUT DOWN WEBLOGIC' check as releases no longer happen at this time.
Also added additional line breaks into email sending functions so they don't get stripped by Outlook.

CM-1467 Add check for letter producer 2nd phase

---

weblogic-batch/cron/track-crontab-changes.sh

Ported script from on-prem to track crontab changes. Using logs dir to store crontab backups for persistence.

CM-1467 track crontab changes

---

weblogic-batch/scripts/track-crontab-changes.sh

Moving script out of cron dir as this is overwritten by docker mount so that crontab can be sourced from S3.
Using scripts dir as this is one that could be useful in other batch containers, like others in that dir.

CM-1467 move crontab check script

---

weblogic-batch/admin/jms/report-stuck-ef-submissions.sh

OE01 submissions from CHS seem to have two `corporateBodyName` elements, which was messing up the formatting of the stuck EF docs report.  The script `weblogic-batch/admin/jms/report-stuck-ef-submissions.sh` has been altered to just extract the first `corporateBodyName`.

Formatting fix for EF stuck docs report

---

weblogic-batch/admin/jms/report-stuck-ef-submissions.sh

Handle case where there are no linefeeds in the xml between the `<attachment>` elements, which 
was causing the report to be garbled.

Fix for live issue seen with report-stuck-ef-submissions.sh  

---

weblogic-batch/process-compliance/process-ch-address-files.sh

Adds a sleep just before removing the processed AFP files, to allow time for the final file to be
fully written and to be out of use, in order to avoid a permission error.
Resolves:
https://companieshouse.atlassian.net/browse/SUP-1107

Add sleep before removing processed AFP files

---

Dockerfile

In order to view stuck FES MS messages using the jms utility scripts, the java classes the messages use must be present on the classpath.  This change references a new version of the jmstool lib that includes more classes to enable viewing/listing of FES messages.
Resolves:
https://companieshouse.atlassian.net/browse/CM-1548

Reference jmstool-0.0.6.jar to allow FES messages to be viewed

---

Dockerfile
weblogic-batch/admin/jms/README.md
weblogic-batch/admin/jms/inject-jms.sh
weblogic-batch/admin/jms/list-all-jms-ef-responses.sh
weblogic-batch/admin/jms/resend-response-jms.sh

Added a script, `list-all-jms-ef-responses.sh`, that lists messages and indicates if they are safe to delete or require investigation.
The following env vars are needed in chips.properties:
`EWF_ADMIN_PROXY_HOST` - proxy server host to allow https access to ewf admin website
`EWF_ADMIN_PROXY_PORT` - proxy server port
`EWF_ADMIN_HOST` - FQDN of the ewf admin website
`EWF_ADMIN_USER` - username to login with
`EWF_ADMIN_PASSWORD` - password to login with
Also updated jmstool library to 0.0.7 to allow EF response messages to be injected with a status (reject or accept).  Previously, it was hardcoded to accept, so rejections couldn't be sent properly.  The associated shell scripts and README have been updated to cater for the extra parameter.

Improve handling of stuck EF JMS response messages

---

Dockerfile

Add OcrRequestMessage class to allow viewing of those JMS messages using utility scripts.
Resolves:
https://companieshouse.atlassian.net/browse/SUP-1125

Reference 0.0.8 of jmstool.jar to include OcrRequestMessage class
